version: '3'
# docker-compose.yml
services:
  # MySQL
  db: 
    image: mysql:5.7.29
    container_name: mysql_host
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: isbn_bookbase
        MYSQL_USER: bookserver
        MYSQL_PASSWORD: bookserver
        TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
        - ~/services/db/data:/var/lib/mysql
    ports:
        - 3306:3306